// MODULE 1.1 - LES VARIABLES (Apex)
// Syntaxe : TypeDeDonnée nomVariable = valeur;
// Complète uniquement les lignes marquées TODO

public class Module1_1_Variables {

    public static void run() {

        // TODO 1 : Mets 'Villa Soleil' à la place de ''
        String nomMaison = '';

        // TODO 2 : Mets 3 à la place de 0
        Integer nbChambres = 0;

        // TODO 3 : Mets 250000.00 à la place de 0
        Decimal prix = 0;

        // TODO 4 : Mets true à la place de false
        Boolean estDisponible = false;

        // Ne modifie pas ces lignes
        System.debug('Nom : ' + nomMaison);
        System.debug('Chambres : ' + nbChambres);
        System.debug('Prix : ' + prix);
        System.debug('Disponible : ' + estDisponible);
    }
}
